
import React, { useState } from 'react';
import { Building2, ChevronDown, ExternalLink, FileText, Gavel, Landmark, Menu, Search, ShieldCheck, User, Users, X } from 'lucide-react';

const states = [
  ['All States','',''], ['Alabama','AL','https://arc-sos.state.al.us/CGI/CORPNAME.MBR/INPUT'], ['Alaska','AK','https://www.commerce.alaska.gov/cbp/main/search/entities'],
  ['Arizona','AZ','https://ecorp.azcc.gov/EntitySearch/Index'], ['Arkansas','AR','https://www.sos.arkansas.gov/corps/search_all.php'],
  ['California','CA','https://bizfileonline.sos.ca.gov/search/business'], ['Colorado','CO','https://www.sos.state.co.us/biz/BusinessEntityCriteriaExt.do'],
  ['Connecticut','CT','https://service.ct.gov/business/s/onlinebusinesssearch'], ['Delaware','DE','https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx'],
  ['Florida','FL','https://search.sunbiz.org/Inquiry/CorporationSearch/ByName'], ['Georgia','GA','https://ecorp.sos.ga.gov/BusinessSearch'],
  ['Hawaii','HI','https://hbe.ehawaii.gov/documents/search.html'], ['Idaho','ID','https://sosbiz.idaho.gov/search/business'],
  ['Illinois','IL','https://apps.ilsos.gov/businessentitysearch/'], ['Indiana','IN','https://bsd.sos.in.gov/publicbusinesssearch'],
  ['Iowa','IA','https://sos.iowa.gov/search/business/search.aspx'], ['Kansas','KS','https://www.kansas.gov/bess/flow/main?execution=e1s1'],
  ['Kentucky','KY','https://web.sos.ky.gov/ftsearch/'], ['Louisiana','LA','https://coraweb.sos.la.gov/commercialsearch/commercialsearch.aspx'],
  ['Maine','ME','https://icrs.informe.org/nei-sos-icrs/ICRS?MainPage=x'], ['Maryland','MD','https://egov.maryland.gov/BusinessExpress/EntitySearch'],
  ['Massachusetts','MA','https://corp.sec.state.ma.us/corpweb/CorpSearch/CorpSearch.aspx'], ['Michigan','MI','https://cofs.lara.state.mi.us/SearchApi/Search/Search'],
  ['Minnesota','MN','https://mblsportal.sos.state.mn.us/Business/Search'], ['Mississippi','MS','https://businesssearch.sos.ms.gov/corp/soskb/csearch.asp'],
  ['Missouri','MO','https://bsd.sos.mo.gov/BusinessEntity/BESearch.aspx'], ['Montana','MT','https://biz.sosmt.gov/search/business'],
  ['Nebraska','NE','https://www.nebraska.gov/sos/corp/corpsearch.cgi'], ['Nevada','NV','https://esos.nv.gov/EntitySearch/OnlineEntitySearch'],
  ['New Hampshire','NH','https://quickstart.sos.nh.gov/online/BusinessInquire'], ['New Jersey','NJ','https://www.njportal.com/DOR/BusinessNameSearch/Search/BusinessName'],
  ['New Mexico','NM','https://portal.sos.state.nm.us/BFS/online/CorporationBusinessSearch'], ['New York','NY','https://apps.dos.ny.gov/publicInquiry/'],
  ['North Carolina','NC','https://www.sosnc.gov/online_services/search/by_title/_Business_Registration'], ['North Dakota','ND','https://firststop.sos.nd.gov/search/business'],
  ['Ohio','OH','https://businesssearch.ohiosos.gov/'], ['Oklahoma','OK','https://www.sos.ok.gov/corp/corpInquiryFind.aspx'],
  ['Oregon','OR','https://sos.oregon.gov/business/Pages/find.aspx'], ['Pennsylvania','PA','https://file.dos.pa.gov/search/business'],
  ['Rhode Island','RI','https://business.sos.ri.gov/CorpWeb/CorpSearch/CorpSearch.aspx'], ['South Carolina','SC','https://businessfilings.sc.gov/BusinessFiling/Entity/Search'],
  ['South Dakota','SD','https://sosenterprise.sd.gov/BusinessServices/Business/FilingSearch.aspx'], ['Tennessee','TN','https://tnbear.tn.gov/Ecommerce/FilingSearch.aspx'],
  ['Texas','TX','https://mycpa.cpa.state.tx.us/coa/'], ['Utah','UT','https://secure.utah.gov/bes/'], ['Vermont','VT','https://bizfilings.vermont.gov/online/BusinessInquire'],
  ['Virginia','VA','https://cis.scc.virginia.gov/EntitySearch/Index'], ['Washington','WA','https://ccfs.sos.wa.gov/#/BusinessSearch'],
  ['West Virginia','WV','https://apps.sos.wv.gov/business/corporations/'], ['Wisconsin','WI','https://www.wdfi.org/apps/CorpSearch/Search.aspx'],
  ['Wyoming','WY','https://wyobiz.wyo.gov/Business/FilingSearch.aspx']
].map(([name,abbr,biz])=>({name,abbr,biz}));

const courtDirectoryByState = Object.fromEntries([
  ['Alabama','https://judicial.alabama.gov/'],['Alaska','https://courts.alaska.gov/'],['Arizona','https://www.azcourts.gov/'],['Arkansas','https://arcourts.gov/'],
  ['California','https://www.courts.ca.gov/find-my-court.htm'],['Colorado','https://www.courts.state.co.us/'],['Connecticut','https://jud.ct.gov/'],['Delaware','https://courts.delaware.gov/'],
  ['Florida','https://www.flcourts.gov/'],['Georgia','https://georgiacourts.gov/'],['Hawaii','https://www.courts.state.hi.us/'],['Idaho','https://isc.idaho.gov/'],
  ['Illinois','https://www.illinoiscourts.gov/'],['Indiana','https://www.in.gov/courts/'],['Iowa','https://www.iowacourts.gov/'],['Kansas','https://www.kscourts.org/'],
  ['Kentucky','https://kycourts.gov/'],['Louisiana','https://www.lasc.org/'],['Maine','https://www.courts.maine.gov/'],['Maryland','https://www.courts.state.md.us/'],
  ['Massachusetts','https://www.mass.gov/orgs/massachusetts-court-system'],['Michigan','https://www.courts.michigan.gov/'],['Minnesota','https://www.mncourts.gov/'],['Mississippi','https://courts.ms.gov/'],
  ['Missouri','https://www.courts.mo.gov/'],['Montana','https://courts.mt.gov/'],['Nebraska','https://supremecourt.nebraska.gov/'],['Nevada','https://nvcourts.gov/'],
  ['New Hampshire','https://www.courts.nh.gov/'],['New Jersey','https://www.njcourts.gov/'],['New Mexico','https://www.nmcourts.gov/'],['New York','https://www.nycourts.gov/'],
  ['North Carolina','https://www.nccourts.gov/'],['North Dakota','https://www.ndcourts.gov/'],['Ohio','https://www.supremecourt.ohio.gov/'],['Oklahoma','https://www.oscn.net/'],
  ['Oregon','https://www.courts.oregon.gov/'],['Pennsylvania','https://www.pacourts.us/'],['Rhode Island','https://www.courts.ri.gov/'],['South Carolina','https://www.sccourts.org/'],
  ['South Dakota','https://ujs.sd.gov/'],['Tennessee','https://www.tncourts.gov/'],['Texas','https://www.txcourts.gov/'],['Utah','https://www.utcourts.gov/'],
  ['Vermont','https://www.vermontjudiciary.org/'],['Virginia','https://www.vacourts.gov/'],['Washington','https://www.courts.wa.gov/'],['West Virginia','https://www.courtswv.gov/'],
  ['Wisconsin','https://www.wicourts.gov/'],['Wyoming','https://www.courts.state.wy.us/']
]);

const counties = [
  ['New York','Albany County','https://iapps.courts.state.ny.us/nyscef/CaseSearch?task=new'],['New York','Bronx County','https://iapps.courts.state.ny.us/nyscef/CaseSearch?task=new'],
  ['New York','Kings County','https://iapps.courts.state.ny.us/nyscef/CaseSearch?task=new'],['New York','Nassau County','https://iapps.courts.state.ny.us/nyscef/CaseSearch?task=new'],
  ['New York','New York County','https://iapps.courts.state.ny.us/nyscef/CaseSearch?task=new'],['New York','Queens County','https://iapps.courts.state.ny.us/nyscef/CaseSearch?task=new'],
  ['New York','Richmond County','https://iapps.courts.state.ny.us/nyscef/CaseSearch?task=new'],['New York','Suffolk County','https://iapps.courts.state.ny.us/nyscef/CaseSearch?task=new'],
  ['New York','Westchester County','https://iapps.courts.state.ny.us/nyscef/CaseSearch?task=new'],['Florida','Miami-Dade County','https://www2.miamidadeclerk.gov/ocs/'],
  ['Florida','Broward County','https://www.browardclerk.org/web2'],['Florida','Orange County','https://myeclerk.myorangeclerk.com/'],['Florida','Palm Beach County','https://appsgp.mypalmbeachclerk.com/eCaseView/'],
  ['California','Los Angeles County','https://www.lacourt.ca.gov/pages/lp/access-a-case/tp/find-case-information/cp/os-civil-case-access'],
  ['Texas','Harris County','https://www.hcdistrictclerk.com/edocs/public/search.aspx'],['Texas','Dallas County','https://courtsportal.dallascounty.org/DALLASPROD'],
  ['Illinois','Cook County','https://www.cookcountyclerkofcourt.org/online-case-information'],['Nevada','Clark County','https://www.clarkcountycourts.us/Portal/']
].map(([state,county,url])=>({state,county,url}));

const inmateByState = {California:'https://ciris.mt.cdcr.ca.gov/', Florida:'https://pubapps.fdc.myflorida.com/OffenderSearch/Search.aspx?TypeSearch=AI', Illinois:'https://idoc.illinois.gov/offender/inmatesearch.html', 'New York':'https://nysdoccslookup.doccs.ny.gov/', Texas:'https://inmate.tdcj.texas.gov/InmateSearch/start.action'};
const links = {bop:'https://www.bop.gov/inmateloc/', courtListener:'https://www.courtlistener.com/', docketAlarm:'https://www.docketalarm.com/', unicourt:'https://unicourt.com/', nsopw:'https://www.nsopw.gov/search-public-sex-offender-registries', pacerCaseLocator:'https://pcl.uscourts.gov/pcl/index.jsf'};

function Logo(){return <div className="logo"><div className="logoMark">RW</div><div><strong>RecordWatchdog</strong><small>Public Records Directory</small></div></div>}
function ButtonLink({href,children,dark=false}){return <a className={`btn ${dark?'dark':''}`} href={href||'#'} target="_blank" rel="noreferrer"><span>{children}</span><ExternalLink size={16}/></a>}
function AdBox({compact=false}){return <div className="ad"><div>Advertisement</div><span className={compact?'compact':''}/></div>}
function Card({icon:Icon,title,text,href,tag}){return <article className="card"><div className="icon"><Icon size={25}/></div>{tag&&<p className="eyebrow small">{tag}</p>}<h3>{title}</h3><p>{text}</p>{href&&<ButtonLink href={href}>Open Search</ButtonLink>}</article>}
function Accent({icon:Icon,orange=false}){return <><div className={`glow ${orange?'orange':''}`}/><div className="water"><Icon size={110}/></div></>}
function Legal({title,label='Legal',children}){return <div><p className="eyebrow">{label}</p><h2>{title}</h2><div className="legal">{children}</div></div>}

export default function App(){
  const [menuOpen,setMenuOpen]=useState(false),[selectedState,setSelectedState]=useState('All States'),[selectedCounty,setSelectedCounty]=useState(''),[name,setName]=useState(''),[street,setStreet]=useState(''),[city,setCity]=useState(''),[sexState,setSexState]=useState(''),[zip,setZip]=useState(''),[radius,setRadius]=useState('5'),[legalPage,setLegalPage]=useState(null);
  const hasState=selectedState!=='All States', state=states.find(s=>s.name===selectedState&&s.name!=='All States'), countyOptions=counties.filter(c=>c.state===selectedState), selectedCountyLink=countyOptions.find(c=>c.county===selectedCounty);
  const businessUrl=state?.biz||'https://www.usa.gov/business', inmateUrl=hasState&&inmateByState[selectedState]?inmateByState[selectedState]:'https://www.usa.gov/state-corrections', lawsuitUrl=selectedCountyLink?.url||(hasState?courtDirectoryByState[selectedState]:'https://www.ncsc.org/information-and-resources/state-court-websites');
  const scrollTo=id=>document.querySelector(id)?.scrollIntoView({behavior:'smooth',block:'start'}), changeState=v=>{setSelectedState(v);setSelectedCounty('')};
  const popular=label=>{const t=String(label).toLowerCase(); if(t.includes('florida'))changeState('Florida'); else if(t.includes('california'))changeState('California'); else if(t.includes('texas'))changeState('Texas'); else if(t.includes('new york')||t.includes('brooklyn')||t.includes('queens')||t.includes('bronx'))changeState('New York'); else if(t.includes('illinois'))changeState('Illinois'); else if(t.includes('georgia'))changeState('Georgia'); if(t.includes('court')||t.includes('lawsuit'))scrollTo('#court'); else if(t.includes('inmate')||t.includes('jail'))scrollTo('#inmates'); else scrollTo('#business')};
  const Chip=({children})=><button className="chip" onClick={()=>popular(children)}>{children}</button>;
  return <div>
    <header><div className="container head"><button className="plain" onClick={()=>scrollTo('#top')}><Logo/></button><nav>{['business','court','inmates','bankruptcy','sex'].map(id=><button key={id} onClick={()=>scrollTo('#'+id)}>{id==='inmates'?'Incarceration':id[0].toUpperCase()+id.slice(1)}</button>)}</nav><button className="menu" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></div>{menuOpen&&<div className="mobile">{['business','court','inmates','bankruptcy','sex'].map(id=><button key={id} onClick={()=>scrollTo('#'+id)}>{id}</button>)}</div>}</header>
    <main id="top">
      <section className="hero"><div className="heroBg"/><div className="container heroGrid"><div><h1>Search Public Records.<br/><span>Find What Matters.</span></h1><p className="heroCopy">Start with a state, then access business entity search, lawsuit records, incarceration records, bankruptcy tools, and sex offender registry resources.</p><div className="heroPills"><span>50 State Directories</span><span>Official Sources</span><span>Privacy-Friendly</span></div><div className="stateBox"><label>Select Your State</label><div className="selectRow"><div className="selectWrap"><select value={selectedState} onChange={e=>changeState(e.target.value)}>{states.map(s=><option key={s.name}>{s.name}</option>)}</select><ChevronDown className="chev"/></div><button onClick={()=>scrollTo('#business')} className="show">Show Options</button></div></div><div className="heroCards">{[['Florida Records','Most searched state'],['California Courts','High traffic lookups'],['Texas Business Search','Popular entity searches']].map(([a,b])=><button key={a} onClick={()=>popular(a)}><strong>{a}</strong><small>{b}</small></button>)}</div></div><div className="side"><AdBox/><div className="trust"><div><ShieldCheck/><p><b>Trusted & Secure</b><br/>Official sources, state court systems, and privacy-friendly navigation.</p></div><div><Search/><p><b>Official Sources</b><br/>Government and court websites prioritized throughout the directory.</p></div></div></div></div></section>
      <section className="quick"><div className="container"><p className="eyebrow">Quick Access</p><h2>Most Searched States</h2><div className="quickGrid">{['Florida','California','Texas','New York','Illinois','Georgia'].map(s=><button key={s} onClick={()=>changeState(s)}><b>{s}</b><span>Popular public record searches</span></button>)}</div></div></section>
      <Section id="business" icon={Building2} eyebrow="Business records" title={hasState?`${selectedState} Business Entity Search`:'Business Entity Search by State'} intro="Open official business entity search tools for LLCs, corporations, registered agents, and filings. Business entity searches are commonly used for due diligence, ownership verification, vendor checks, and researching active or dissolved companies." chips={['LLC Verification','Corporate Filings','Registered Agents']}><Card icon={Building2} title={hasState?`${selectedState} Entity Search`:'Select a State First'} text={hasState?'Look up official Secretary of State business filings.':'Choose a state above to display the official business search link.'} href={hasState?businessUrl:undefined} tag={hasState?'Official source':'State required'}/><Card icon={FileText} title="Business Filing Tips" text="Search by exact name, partial name, officer, registered agent, or entity number when available."/><AdBox compact/></Section>
      <section id="court" className="section alt"><Accent icon={Gavel}/><div className="container in"><p className="eyebrow">Lawsuit records</p><h2>{hasState?`${selectedState} Lawsuit Records`:'Lawsuit Records by State and County'}</h2><p className="intro">{hasState?`Choose a county within ${selectedState} to open lawsuit and civil case lookup tools. Most civil lawsuits, judgments, and local court filings are managed at the county level.`:'Select a state from the hero section above to load county court records. Most lawsuit and civil court searches begin with the county clerk or local court system.'}</p><div className="chips"><span>Civil Cases</span><span>Judgments</span><span>County Court Records</span></div><div className="grid three"><Card icon={Gavel} title={hasState?`${selectedState} Court Directory`:'Select a State First'} text={hasState?'Use official court and clerk resources for lawsuit and civil case records.':'Choose a state in the hero section above to load county lawsuit record options.'} tag={hasState?'Lawsuit source':'State required'}/><article className="card"><div className="icon"><Gavel/></div><p className="eyebrow small">County lookup</p><h3>Choose County</h3><p>Most civil lawsuits and local court records are maintained at the county level.</p><select className="full" value={selectedCounty} onChange={e=>setSelectedCounty(e.target.value)} disabled={!hasState}><option>{hasState?'Select County':'Select a state above first'}</option>{countyOptions.map(c=><option key={c.county}>{c.county}</option>)}</select><ButtonLink href={lawsuitUrl}>{selectedCountyLink?'Open Lawsuit Search':'Court Directory'}</ButtonLink></article><AdBox compact/></div></div></section>
      <div className="container adBreak"><AdBox compact/></div>
      <Section id="bankruptcy" icon={FileText} eyebrow="Federal records" title="Bankruptcy & Federal Case Search" intro="Search federal bankruptcy and court systems using PACER and related legal research tools. Bankruptcy filings are maintained in the federal court system and may include Chapter 7, Chapter 11, and Chapter 13 cases." chips={['Federal Court Records','Chapter 7 & 11','PACER Search']}><div className="searchRow"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Person or business name"/><ButtonLink href={links.pacerCaseLocator}>Continue to PACER</ButtonLink></div><Card icon={FileText} title="CourtListener" text="Free federal court opinions, RECAP archives, and docket research tools." href={links.courtListener} tag="Free research"/><Card icon={Search} title="Docket Alarm" text="Advanced litigation analytics, federal court dockets, and legal intelligence tools." href={links.docketAlarm} tag="Premium analytics"/><Card icon={Building2} title="UniCourt" text="Enterprise court analytics, litigation tracking, and federal docket intelligence platform." href={links.unicourt} tag="Legal intelligence"/></Section>
      <section id="inmates" className="section alt"><Accent icon={Landmark}/><div className="container in"><p className="eyebrow">Incarceration records</p><h2>Incarceration Records</h2><p className="intro">{hasState?`Search ${selectedState} correctional records or federal inmate custody records using official incarceration databases. State systems usually track prison inmates, while county jail systems may maintain separate local detention records.`:'Select a state above to load state incarceration records, or use the federal inmate locator below. State and federal inmate systems are maintained separately.'}</p><div className="chips"><span>State Corrections</span><span>Federal Inmates</span><span>County Jail Records</span></div><div className="searchRow"><input value={name} onChange={e=>setName(e.target.value)} placeholder="First and last name"/><ButtonLink href={inmateUrl}>{hasState?`Open ${selectedState} Search`:'Open State Directory'}</ButtonLink></div><div className="grid three"><Card icon={ShieldCheck} title="Federal Inmate Locator" text="Search Bureau of Prisons records for federal inmates, federal convictions, and U.S. federal custody records." href={links.bop}/><Card icon={Users} title="County Jail Directory" text="Search county jail rosters, sheriff inmate databases, and local detention records by county or sheriff office." href="https://www.usa.gov/local-governments"/><AdBox compact/></div></div></section>
      <section id="sex" className="section"><Accent icon={ShieldCheck} orange/><div className="container in"><p className="eyebrow">Public safety</p><h2>National Sex Offender Registry</h2><p className="intro">Search the official NSOPW registry by name or address-radius lookup. The National Sex Offender Public Website aggregates participating state, territorial, and tribal registry systems into one searchable platform.</p><div className="chips"><span>National Registry</span><span>Address Radius Search</span><span>Public Safety Records</span></div><div className="grid two"><article className="card big"><h3><User/> Name Lookup</h3><input value={name} onChange={e=>setName(e.target.value)} placeholder="First and last name"/><ButtonLink href={links.nsopw}>Open Name Search</ButtonLink></article><article className="card big"><h3><Search/> Address Radius Lookup</h3><div className="inputs"><input value={street} onChange={e=>setStreet(e.target.value)} placeholder="Street address"/><input value={city} onChange={e=>setCity(e.target.value)} placeholder="City"/><input value={sexState} onChange={e=>setSexState(e.target.value)} placeholder="State"/><input value={zip} onChange={e=>setZip(e.target.value)} placeholder="ZIP code"/><select value={radius} onChange={e=>setRadius(e.target.value)}><option>1</option><option>5</option><option>10</option><option>25</option></select></div><ButtonLink href={links.nsopw} dark>Open Address Search</ButtonLink></article></div><p className="note">Address searches are completed on the official NSOPW website. RecordWatchdog does not host registry records.</p></div></section>
      <section className="bottom"><div className="container"><article className="content"><p className="eyebrow">Most Popular Searches</p><h2>Most Searched States</h2><div className="chips">{['Florida Public Records','California Court Records','Texas Business Search','New York Inmate Search','Illinois Court Search','Georgia Business Entity Search','Delaware LLC Search','Florida Arrest Records'].map(x=><Chip key={x}>{x}</Chip>)}</div></article><AdBox/></div></section>
    </main>
    {legalPage&&<div className="modalBg"><div className="modal"><button className="close" onClick={()=>setLegalPage(null)}><X/></button>{legalPage==='privacy'&&<Legal title="Privacy Policy"><p>RecordWatchdog respects your privacy and is designed primarily as a directory of official public-record resources.</p><p>We do not host criminal records, court records, inmate databases, bankruptcy records, or sex offender registry records directly on our servers.</p><p>We may use analytics, cookies, and advertising technologies such as Google AdSense to improve the website and support its operation.</p><p>Users should verify all records directly with the official source.</p></Legal>}{legalPage==='terms'&&<Legal title="Terms of Use"><p>RecordWatchdog is an informational directory that helps users locate public-record resources and official third-party websites.</p><p>This website is not a consumer reporting agency under the Fair Credit Reporting Act and may not be used for employment screening, tenant screening, credit eligibility, or similar FCRA-regulated purposes.</p></Legal>}{legalPage==='about'&&<Legal title="About RecordWatchdog" label="About"><p>RecordWatchdog organizes business records, court records, incarceration records, bankruptcy resources, and registry search tools into one streamlined public-records directory.</p></Legal>}{legalPage==='contact'&&<Legal title="Contact Us" label="Contact"><p>For general inquiries, corrections, business opportunities, or legal requests, please contact:</p><div className="email">niko@nwbventures.com</div></Legal>}{legalPage==='dmca'&&<Legal title="DMCA Policy"><p>RecordWatchdog respects intellectual property rights and responds to valid copyright complaints under the Digital Millennium Copyright Act.</p><p>If you believe copyrighted material has been used improperly on this website, please send a notice including your contact information, a description of the copyrighted work, the URL of the material, a good-faith statement, and your physical or electronic signature.</p><div className="email">niko@nwbventures.com</div></Legal>}</div></div>}
    <footer><div className="container foot"><Logo/><div>{['privacy','terms','about','contact','dmca'].map(p=><button key={p} onClick={()=>setLegalPage(p)}>{p==='dmca'?'DMCA':p[0].toUpperCase()+p.slice(1)}</button>)}</div></div></footer>
  </div>
}

function Section({id,icon,eyebrow,title,intro,chips,children}){const Icon=icon;return <section id={id} className="section"><Accent icon={Icon} orange/><div className="container in"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p className="intro">{intro}</p><div className="chips">{chips.map(c=><span key={c}>{c}</span>)}</div><div className="grid three">{children}</div></div></section>}
